# libretro-netplay-registry Docker Compose
#
# Usage:
#
# 1. Run `docker-compose up`
# 2. Visit http://localhost:8000 in your browser
# 3. If the screen is white, it's working

version: "2"

services:
  php:
    image: php:5-cli
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php -S 0.0.0.0:8000
